# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title modelddsPLSCpp_Rcpp
#' @description
#' Build a ddsPLS model once the bootstrap operations has allowed to find a correct lambda.
#' @name modelddsPLSCpp_Rcpp.
#' @param U The weights for X part.
#' @param V The weights for Y part.
#' @param X The matrix of X part.
#' @param Y The matrix of X part.
#' @param lambdas The to be tested values for lambda.
#' @param R The number of components to build.
#' @param n The number of observations.
#' @param p The number of variables of X part.
#' @param q The number of variables of Y part.
#'
#' @export
modelddsPLSCpp_Rcpp <- function(U, V, X, Y, lambdas, R, n, p, q) {
    .Call('_ddsPLS2_modelddsPLSCpp_Rcpp', PACKAGE = 'ddsPLS2', U, V, X, Y, lambdas, R, n, p, q)
}

#' @title bootstrap_Rcpp
#' @description
#' Start the bootstrap operations.
#' @name bootstrap_Rcpp.
#' @param U The weights for X part.
#' @param V The weights for Y part.
#' @param X The matrix of X part.
#' @param Y The matrix of X part.
#' @param lambdas The to be tested values for lambda.
#' @param lambda_prev The previously selected values for lambda.
#' @param R The number of components to build.
#' @param n_B The number of bootstrap samples to generate and analyse.
#' @param n The number of observations.
#' @param p The number of variables of X part.
#' @param q The number of variables of Y part.
#' @param N_lambdas The number of to be tested values for lambda.
#'
#' @export
bootstrap_Rcpp <- function(U, V, X, Y, lambdas, lambda_prev, R, n_B, doBoot, n, p, q, N_lambdas) {
    .Call('_ddsPLS2_bootstrap_Rcpp', PACKAGE = 'ddsPLS2', U, V, X, Y, lambdas, lambda_prev, R, n_B, doBoot, n, p, q, N_lambdas)
}

